package org.greenpipe.workspace.model.bean;

// Generated 2014-10-27 17:08:14 by Hibernate Tools 3.4.0.CR1

/**
 * CookbookDependency generated by hbm2java
 */
public class CookbookDependency implements java.io.Serializable {

	private Integer id;
	private Cookbook cookbookByDestinationId;
	private Cookbook cookbookBySourceId;

	public CookbookDependency() {
	}

	public CookbookDependency(Cookbook cookbookByDestinationId,
			Cookbook cookbookBySourceId) {
		this.cookbookByDestinationId = cookbookByDestinationId;
		this.cookbookBySourceId = cookbookBySourceId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cookbook getCookbookByDestinationId() {
		return this.cookbookByDestinationId;
	}

	public void setCookbookByDestinationId(Cookbook cookbookByDestinationId) {
		this.cookbookByDestinationId = cookbookByDestinationId;
	}

	public Cookbook getCookbookBySourceId() {
		return this.cookbookBySourceId;
	}

	public void setCookbookBySourceId(Cookbook cookbookBySourceId) {
		this.cookbookBySourceId = cookbookBySourceId;
	}

}
