package org.greenpipe.workspace.model.bean;

// Generated 2014-10-27 17:08:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Vm generated by hbm2java
 */
public class Vm implements java.io.Serializable {

	private Integer id;
	private Workspace workspace;
	private String provider;
	private String size;
	private String hostname;
	private String username;
	private String password;
	private String image;
	private String state;
	private Date createTime;
	private Date updateTime;

	public Vm() {
	}

	public Vm(String provider, String size, String hostname, String username,
			String password, String image, String state, Date createTime,
			Date updateTime) {
		this.provider = provider;
		this.size = size;
		this.hostname = hostname;
		this.username = username;
		this.password = password;
		this.image = image;
		this.state = state;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Vm(Workspace workspace, String provider, String size,
			String hostname, String username, String password, String image,
			String state, Date createTime, Date updateTime) {
		this.workspace = workspace;
		this.provider = provider;
		this.size = size;
		this.hostname = hostname;
		this.username = username;
		this.password = password;
		this.image = image;
		this.state = state;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Workspace getWorkspace() {
		return this.workspace;
	}

	public void setWorkspace(Workspace workspace) {
		this.workspace = workspace;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
