package org.greenpipe.workspace.model.bean;

// Generated 2014-10-27 17:08:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Workspace generated by hbm2java
 */
public class Workspace implements java.io.Serializable {

	private Integer id;
	private User user;
	private int server;
	private String provider;
	private String vmSize;
	private int vmNumber;
	private String description;
	private String state;
	private String isDefault;
	private String message;
	private Date createTime;
	private Date updateTime;
	private Set workspaceCookbookAssociations = new HashSet(0);
	private Set vms = new HashSet(0);

	public Workspace() {
	}

	public Workspace(int server, String provider, String vmSize, int vmNumber,
			String description, String state, String isDefault, String message,
			Date createTime, Date updateTime) {
		this.server = server;
		this.provider = provider;
		this.vmSize = vmSize;
		this.vmNumber = vmNumber;
		this.description = description;
		this.state = state;
		this.isDefault = isDefault;
		this.message = message;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Workspace(User user, int server, String provider, String vmSize,
			int vmNumber, String description, String state, String isDefault,
			String message, Date createTime, Date updateTime,
			Set workspaceCookbookAssociations, Set vms) {
		this.user = user;
		this.server = server;
		this.provider = provider;
		this.vmSize = vmSize;
		this.vmNumber = vmNumber;
		this.description = description;
		this.state = state;
		this.isDefault = isDefault;
		this.message = message;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.workspaceCookbookAssociations = workspaceCookbookAssociations;
		this.vms = vms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getServer() {
		return this.server;
	}

	public void setServer(int server) {
		this.server = server;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public String getVmSize() {
		return this.vmSize;
	}

	public void setVmSize(String vmSize) {
		this.vmSize = vmSize;
	}

	public int getVmNumber() {
		return this.vmNumber;
	}

	public void setVmNumber(int vmNumber) {
		this.vmNumber = vmNumber;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getWorkspaceCookbookAssociations() {
		return this.workspaceCookbookAssociations;
	}

	public void setWorkspaceCookbookAssociations(
			Set workspaceCookbookAssociations) {
		this.workspaceCookbookAssociations = workspaceCookbookAssociations;
	}

	public Set getVms() {
		return this.vms;
	}

	public void setVms(Set vms) {
		this.vms = vms;
	}

}
