package org.greenpipe.workspace.model.bean;

// Generated 2014-10-27 17:08:14 by Hibernate Tools 3.4.0.CR1

/**
 * WorkspaceCookbookAssociation generated by hbm2java
 */
public class WorkspaceCookbookAssociation implements java.io.Serializable {

	private Integer id;
	private Cookbook cookbook;
	private Workspace workspace;

	public WorkspaceCookbookAssociation() {
	}

	public WorkspaceCookbookAssociation(Cookbook cookbook, Workspace workspace) {
		this.cookbook = cookbook;
		this.workspace = workspace;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cookbook getCookbook() {
		return this.cookbook;
	}

	public void setCookbook(Cookbook cookbook) {
		this.cookbook = cookbook;
	}

	public Workspace getWorkspace() {
		return this.workspace;
	}

	public void setWorkspace(Workspace workspace) {
		this.workspace = workspace;
	}

}
