package org.greenpipe.workspace.states;

public enum WorkspaceState {
	// Login
	LOGIN_SUCCESSFUL, LOGIN_FAILED,
	
	// Parse
	PARSE_SUCCESSFUL, PARSE_FAILED,
	
	// Resources
	RESOURCES_SUCCESSFUL, RESOURCES_FAILED,
	
	// Create
	CREATE_NEW, CREATE_QUEUED, CREATE_INITIALIZING, CREATE_SUCCESSFUL, CREATE_FAILED,
	
	// Bootstrap
	BOOTSTRAP_NEW, BOOTSTRAP_QUEUED, BOOTSTRAP_INITIALIZING, BOOTSTRAP_SUCCESSFUL, BOOTSTRAP_FAILED,
	
	// Delete
	DELETE_NEW, DELETE_QUEUED, DELETE_INITIALIZING, DELETE_SUCCESSFUL, DELETE_FAILED,
	
	// Start
	START_NEW, START_QUEUED, START_INITIALIZING, START_SUCCESSFUL, START_FAILED,
	
	// Stop
	STOP_NEW, STOP_QUEUED, STOP_INITIALIZING, STOP_SUCCESSFUL, STOP_FAILED,
	
	// Restart
	RESTART_NEW, RESTART_QUEUED, RESTART_INITIALIZING, RESTART_SUCCESSFUL, RESTART_FAILED,
	
	// DRM
	DRM_INITIALIZING, DRM_SUCCESSFUL, DRM_FAILED,
	
	// Set default
	SET_DEFAULT_SUCCESSFUL, SET_DEFAULT_FAILED
}
